---
name: mysql
description: "Stack for my MySQL Database"
components:
  database:
    charm: cs:mysql-58
    config:
      block-size: 6
      dataset-size: '81%'
    num_units: 1
provides:
  db:
    forward: database:db
requires:
  slave:
    forward: database:slave
